version: '3.4'

services:
  postgres:
    image: postgres
    hostname: postgres
  eventstoreapi:
    image: ${DOCKER_REGISTRY-}eventstoreapi
    build:
      context: .
      dockerfile: src/Services/EventStore/EventStore.API/Dockerfile
    depends_on:
      - postgres
  cookbookapi:
    image: ${DOCKER_REGISTRY-}cookbookapi
    build:
      context: .
      dockerfile: src/Services/CookBook/CookBook.API/Dockerfile

volumes:
  postgres-data:


