version: '3.4'

services:
  postgres:
    image: postgres
    hostname: postgres
  eventstoreapi:
    image: ${DOCKER_REGISTRY-}eventstoreapi
    build:
      context: .
      dockerfile: src/Services/EventStore/EventStore.API/Dockerfile
    depends_on:
      - postgres
  cookbookapi:
    image: ${DOCKER_REGISTRY-}cookbookapi
    build:
      context: .
      dockerfile: src/Services/CookBook/CookBook.API/Dockerfile
  interactionsapi:
    image: ${DOCKER_REGISTRY-}interactionsapi
    build:
      context: .
      dockerfile: src/Services/Interactions/Interactions.API/Dockerfile
  analyticsapi:
    image: ${DOCKER_REGISTRY-}analyticsapi
    build:
      context: .
      dockerfile: src/Services/Analytics/Analytics.API/Dockerfile
  usersapi:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: src/Services/Users/Users.API/Dockerfile

volumes:
  postgres-data:





